on: [push, pull_request]
name: "Check code quality"

defaults:
  run:
    shell: bash

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install $(grep -E '^(black|flake8|isort|mypy)' requirements.txt)
      - run: make lint
